# Integrate Project Sprint - Data Cleaning

Thabang Ndhlovu, 2024

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("datasets/insurance_claims_raw.xlsx")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          998 non-null    float64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   datetime64[ns]
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            998 non-null    float64
 7   policy_annual_premium        997 non-null    float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      999 non-null    object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              998 non-null    object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                998 non-null    float64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   datetime64[ns]
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        907 non-null    object
 22  incident_state               998 non-null    object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           996 non-null    float64
 32  injury_claim                 999 non-null    float64
 33  property_claim               999 non-null    float64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: datetime64[ns](2), float64(8), int64(11), object(19)
memory usage: 312.6+ KB

In [4]:
df.describe()

,months_as_customer,age,policy_number,policy_bind_date,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,capital-gains,capital-loss,...,incident_hour_of_the_day,number_of_vehicles_involved,bodily_injuries,witnesses,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_year,_c39
count,1000.000000,998.000000,1000.000000,1000,998.000000,997.000000,1.000000e+03,1000.000000,998.000000,1000.000000,...,1000.000000,1000.00000,1000.000000,1000.000000,996.000000,999.000000,999.000000,1000.000000,1000.000000,0.0
mean,203.954000,38.962926,546238.648000,2002-02-08 04:40:47.999999872,1134.268537,1257.001113,1.101000e+06,501214.488000,25176.452906,-26793.700000,...,11.644000,1.83900,0.992000,1.487000,52767.469880,7434.944945,7398.628629,37928.950000,2005.103000,NaN
min,0.000000,19.000000,100804.000000,1990-01-08 00:00:00,500.000000,433.330000,-1.000000e+06,430104.000000,0.000000,-111100.000000,...,0.000000,1.00000,0.000000,0.000000,100.000000,0.000000,0.000000,70.000000,1995.000000,NaN
25%,115.750000,32.000000,335980.250000,1995-09-19 00:00:00,500.000000,1090.320000,0.000000e+00,448404.500000,0.000000,-51500.000000,...,6.000000,1.00000,0.000000,1.000000,41812.500000,4290.000000,4440.000000,30292.500000,2000.000000,NaN
50%,199.500000,38.000000,533135.000000,2002-04-01 12:00:00,1000.000000,1257.830000,0.000000e+00,466445.500000,0.000000,-23250.000000,...,12.000000,1.00000,1.000000,1.000000,57935.000000,6780.000000,6750.000000,42100.000000,2005.000000,NaN
75%,276.250000,44.000000,759099.750000,2008-04-21 12:00:00,2000.000000,1415.740000,0.000000e+00,603251.000000,51075.000000,0.000000,...,17.000000,3.00000,2.000000,2.000000,70620.000000,11310.000000,10890.000000,50822.500000,2010.000000,NaN
max,479.000000,64.000000,999435.000000,2015-02-22 00:00:00,2000.000000,2047.590000,1.000000e+07,620962.000000,100500.000000,0.000000,...,23.000000,4.00000,2.000000,3.000000,114920.000000,21450.000000,23670.000000,79560.000000,2015.000000,NaN
std,115.113174,9.135425,257063.005276,NaN,611.251914,244.265051,2.297407e+06,71701.610941,27877.379027,28104.096686,...,6.951373,1.01888,0.820127,1.111335,26405.348039,4883.158265,4827.050887,18886.252893,6.015861,NaN

In [5]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
months_as_customer,328,228,134,256,228,256,137,165,27,212,...,286,257,94,124,141,3,285,130,458,456
age,48.0,42.0,29.0,41.0,44.0,39.0,34.0,37.0,33.0,42.0,...,43.0,44.0,26.0,28.0,30.0,38.0,41.0,34.0,62.0,60.0
policy_number,521585,342868,687698,227811,367455,104594,413978,429027,485665,636550,...,663190,109392,215278,674570,681486,941851,186934,918516,533940,556080
policy_bind_date,2014-10-17 00:00:00,2006-06-27 00:00:00,2000-09-06 00:00:00,1990-05-25 00:00:00,2014-06-06 00:00:00,2006-10-12 00:00:00,2000-06-04 00:00:00,1990-02-03 00:00:00,1997-02-05 00:00:00,2011-07-25 00:00:00,...,1994-02-05 00:00:00,2006-07-12 00:00:00,2007-10-24 00:00:00,2001-12-08 00:00:00,2007-03-24 00:00:00,1991-07-16 00:00:00,2014-01-05 00:00:00,2003-02-17 00:00:00,2011-11-18 00:00:00,1996-11-11 00:00:00
policy_state,OH,IN,OH,IL,IL,OH,IN,IL,IL,IL,...,IL,OH,IN,OH,IN,OH,IL,OH,IL,OH
policy_csl,250/500,250/500,100/300,250/500,500/1000,250/500,250/500,100/300,100/300,100/300,...,100/300,100/300,100/300,250/500,500/1000,500/1000,100/300,250/500,500/1000,250/500
policy_deductable,1000.0,2000.0,2000.0,2000.0,1000.0,1000.0,1000.0,1000.0,500.0,500.0,...,500.0,1000.0,500.0,1000.0,1000.0,1000.0,1000.0,500.0,2000.0,1000.0
policy_annual_premium,1406.91,1197.22,1413.14,1415.74,1583.91,1351.1,1333.35,1137.03,1442.99,1315.68,...,1564.43,1280.88,722.66,1235.14,1347.04,1310.8,1436.79,1383.49,1356.92,766.19
umbrella_limit,0,5000000,5000000,6000000,6000000,0,0,0,0,0,...,3000000,0,0,0,0,0,0,3000000,5000000,0
insured_zip,466132,468176,430632,608117,610706,478456,441716,603195,601734,600983,...,477644,433981,433696,443567,430665,431289,608177,442797,441714,612260
insured_sex,MALE,MALE,FEMALE,FEMALE,MALE,FEMALE,MALE,MALE,FEMALE,MALE,...,FEMALE,MALE,MALE,MALE,MALE,FEMALE,FEMALE,FEMALE,MALE,FEMALE
insured_education_level,MD,MD,PhD,PhD,Associate,PhD,NaN,Associate,PhD,PhD,...,MD,MD,MD,MD,High School,Masters,PhD,Masters,Associate,Associate
insured_occupation,craft-repair,machine-op-inspct,sales,armed-forces,sales,tech-support,prof-specialty,tech-support,other-service,priv-house-serv,...,prof-specialty,other-service,exec-managerial,exec-managerial,sales,craft-repair,prof-specialty,armed-forces,handlers-cleaners,sales
insured_hobbies,sleeping,reading,board-games,NaN,NaN,bungie-jumping,board-games,base-jumping,golf,camping,...,movies,basketball,camping,camping,bungie-jumping,paintball,sleeping,bungie-jumping,base-jumping,kayaking
insured_relationship,husband,other-relative,own-child,unmarried,unmarried,unmarried,husband,unmarried,own-child,wife,...,unmarried,other-relative,husband,husband,own-child,unmarried,wife,other-relative,wife,husband
capital-gains,53300.0,0.0,35100.0,48900.0,66000.0,0.0,0.0,0.0,0.0,0.0,...,77500.0,59400.0,50300.0,0.0,0.0,0.0,70900.0,35100.0,0.0,0.0
capital-loss,0,0,0,-62400,-46000,0,-77000,0,0,-39300,...,-32800,-32200,0,-32100,-82100,0,0,0,0,0
incident_date,2015-01-25 00:00:00,2015-01-21 00:00:00,2015-02-22 00:00:00,2015-01-10 00:00:00,2015-02-17 00:00:00,2015-01-02 00:00:00,2015-01-13 00:00:00,2015-02-27 00:00:00,2015-01-30 00:00:00,2015-01-05 00:00:00,...,2015-01-31 00:00:00,2015-02-06 00:00:00,2015-01-23 00:00:00,2015-02-17 00:00:00,2015-01-22 00:00:00,2015-02-22 00:00:00,2015-01-24 00:00:00,2015-01-23 00:00:00,2015-02-26 00:00:00,2015-02-26 00:00:00
incident_type,Single Vehicle Collision,Vehicle Theft,Multi-vehicle Collision,Single Vehicle Collision,Vehicle Theft,Multi-vehicle Collision,Multi-vehicle Collision,Multi-vehicle Collision,Single Vehicle Collision,Single Vehicle Collision,...,Single Vehicle Collision,Single Vehicle Collision,Multi-vehicle Collision,Multi-vehicle Collision,Parked Car,Single Vehicle Collision,Single Vehicle Collision,Multi-vehicle Collision,Single Vehicle Collision,Parked Car
collision_type,Side Collision,?,Rear Collision,Front Collision,?,Rear Collision,Front Collision,Front Collision,Front Collision,Rear Collision,...,Rear Collision,Rear Collision,Front Collision,Side Collision,?,Front Collision,Rear Collision,Side Collision,Rear Collision,?
incident_severity,Major Damage,Minor Damage,Minor Damage,Major Damage,Minor Damage,Major Damage,Minor Damage,Total Loss,Total Loss,Total Loss,...,Minor Damage,Total Loss,Major Damage,Total Loss,Minor Damage,Minor Damage,Major Damage,Minor Damage,Major Damage,Minor Damage
authorities_contacted,Police,Police,Police,Police,NaN,Fire,Police,Police,Police,Other,...,Fire,Other,Fire,Other,NaN,Fire,Fire,Police,Other,Police
incident_state,SC,VA,NY,OH,NY,SC,NY,VA,WV,NC,...,NY,WV,OH,OH,SC,NC,SC,NC,NY,WV
incident_city,Columbus,Riverwood,Columbus,Arlington,Arlington,Arlington,Springfield,Columbus,Arlington,Hillsdale,...,Northbrook,Riverwood,Springfield,Hillsdale,Northbend,Northbrook,Northbend,Arlington,Arlington,Columbus
incident_location,9935 4th Drive,6608 MLK Hwy,7121 Francis Lane,6956 Maple Drive,3041 3rd Ave,8973 Washington St,5846 Weaver Drive,3525 3rd Hwy,4872 Rock Ridge,3066 Francis Ave,...,4755 1st St,5312 Francis Ridge,1705 Weaver St,1643 Washington Hwy,6516 Solo Drive,6045 Andromedia St,3092 Texas Drive,7629 5th St,6128 Elm Lane,1416 Cherokee Ridge
incident_hour_of_the_day,5,8,7,5,20,19,0,23,21,14,...,18,21,6,20,6,20,23,4,2,6
number_of_vehicles_involved,1,1,3,1,1,3,3,3,1,1,...,1,1,3,3,1,1,1,3,1,1
property_damage,YES,?,NO,?,NO,NO,?,?,NO,NO,...,?,NO,YES,?,?,YES,YES,?,?,?
bodily_injuries,1,0,2,1,0,0,0,2,1,2,...,2,0,1,0,1,0,2,2,0,0
witnesses,2,0,3,2,1,2,0,2,1,1,...,2,1,2,1,2,1,3,3,1,3
police_report_available,YES,?,NO,NO,NO,NO,?,YES,YES,?,...,YES,NO,YES,?,YES,?,?,YES,YES,?
total_claim_amount,71610.0,5070.0,34650.0,63400.0,6500.0,64100.0,78650.0,51590.0,27700.0,42300.0,...,34290.0,46980.0,36700.0,60200.0,6480.0,87200.0,108480.0,67500.0,46980.0,5060.0
injury_claim,6510.0,780.0,7700.0,6340.0,1300.0,6410.0,21450.0,9380.0,2770.0,4700.0,...,3810.0,0.0,3670.0,6020.0,540.0,17440.0,18080.0,7500.0,5220.0,460.0
property_claim,13020.0,780.0,3850.0,6340.0,650.0,6410.0,7150.0,9380.0,2770.0,4700.0,...,3810.0,5220.0,7340.0,6020.0,1080.0,8720.0,18080.0,7500.0,5220.0,920.0
vehicle_claim,52080,3510,23100,50720,4550,51280,50050,32830,22160,32900,...,26670,41760,25690,48160,4860,61040,72320,52500,36540,3680
auto_make,Saab,Mercedes,Dodge,Chevrolet,Accura,Saab,Nissan,Audi,Toyota,Saab,...,Jeep,Accura,Nissan,Volkswagen,Honda,Honda,Volkswagen,Suburu,Audi,Mercedes
auto_model,92x,E400,RAM,Tahoe,RSX,95,Pathfinder,A5,Camry,92x,...,Grand Cherokee,TL,Pathfinder,Passat,Civic,Accord,Passat,Impreza,A5,E400
auto_year,2004,2007,2007,2014,2009,2003,2012,2015,2012,1996,...,2013,2002,2010,2012,1996,2006,2015,1996,1998,2007
fraud_reported,Y,Y,N,Y,N,Y,N,N,N,N,...,N,N,N,N,N,N,N,N,N,N
_c39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Drop all NaNs
df.replace("?", float("NaN"), inplace=True)
df = df.drop("_c39", axis=1)


# Impute missing values with mode and median values
for column in df.columns:
    if pd.api.types.is_object_dtype(df[column]):
        df[column] = df[column].fillna(df[column].mode()[0])
    elif pd.api.types.is_numeric_dtype(df[column]):
        df[column] = df[column].fillna(df[column].median())


# Remove outliers using z-score
threshold=1.5
for column in df:
    if pd.api.types.is_float_dtype(df[column]):
        q1 = df[column].quantile(0.25)
        q3 = df[column].quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - (threshold * iqr)
        upper_bound = q3 + (threshold * iqr)
        df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

        
# save file
df.to_excel("datasets/insurance_claims_clean.xlsx", index=False)